[package]
name = "persist0-gpu"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
persist0 = { path = "..", default-features = false }
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide", rev = "b0f961df" }
cuda-host   = { git = "https://github.com/NVlabs/cuda-oxide", rev = "b0f961df" }
cuda-core   = "0.3.1"
rand = "0.10"